fictionpress.com:
  scraper: 'FFNScraper'
  data:
    image_background: '#fff'
    summary: "#profile_top div.xcontrast_txt"
    meta: "#profile_top span.xgray.xcontrast_txt"
    title: "#profile_top .xcontrast_txt"
    author: "//a[starts-with(@href, '/u/')]"
    chapter_urls: "#chap_select"
    chapter_titles: '#chap_select option'
    chapter_content: "#storytext"

fanfiction.net:
  scraper: 'FFNScraper'
  data:
    image_background: '#fff'
    summary: "#profile_top div.xcontrast_txt"
    meta: "#profile_top span.xgray.xcontrast_txt"
    title: "#profile_top .xcontrast_txt"
    author: "//a[starts-with(@href, '/u/')]"
    chapter_urls: "#chap_select"
    chapter_titles: '#chap_select option'
    chapter_content: "#storytext"


forum.questionablequesting.com:
  scraper: 'ForumScraper'
  data:
    image_background: '#EAEBEB'
    post: '#messageList .message'
    threadmark: '.message.hasThreadmark'
    overlay_threadmark: '.overlayScroll.threadmarks li'
    chapter_pub_date: '.messageInfo .messageMeta .datePermalink .DateTime'
    chapter_edit_date: '.messageInfo .editDate .DateTime'
    story_pub_date: '.message .primaryContent .messageMeta .datePermalink'
    avatar: '#messageList .message .avatar img'
    threadmark_list_item: '.threadmarkItem a'
    chapter_threadmark_text: 'Threadmark:'
    chapter_content: '.messageContent .messageText'

forums.sufficientvelocity.com:
  scraper: 'ForumScraper'
  data:
    image_background: '#282828'
    post: '#messageList .message'
    threadmark: '.message.hasThreadmark'
    overlay_threadmark: '.ThreadmarkIndex .threadmarkList li'
    chapter_pub_date: '.messageInfo .messageMeta .datePermalink .DateTime'
    chapter_edit_date: '.messageInfo .editDate .DateTime'
    story_pub_date: '.message .primaryContent .messageMeta .datePermalink'
    avatar: '#messageList .message .avatar img'
    threadmark_list_item: '.threadmarkListItem a'
    chapter_threadmark_text: 'Threadmarks:'
    chapter_content: '.messageContent .messageText'

forums.spacebattles.com:
  scraper: 'ForumScraper'
  data:
    image_background: '#191F2D'
    post: '#messageList .message'
    threadmark: '.message.hasThreadmark'
    overlay_threadmark: '.ThreadmarkIndex .threadmarkList li'
    chapter_pub_date: '.messageInfo .messageMeta .datePermalink .DateTime'
    chapter_edit_date: '.messageInfo .editDate .DateTime'
    story_pub_date: '.message .primaryContent .messageMeta .datePermalink'
    avatar: '#messageList .message .avatar img'
    threadmark_list_item: '.threadmarkListItem a'
    chapter_threadmark_text: 'Threadmarks:'
    chapter_content: '.messageContent .messageText'

alternatehistory.com:
  scraper: 'ForumScraper'
  data:
    image_background: '#EAEBEB'
    post: '#messageList .message'
    threadmark: '.message.hasThreadmark'
    overlay_threadmark: '.ThreadmarkIndex .threadmarkList li'
    chapter_pub_date: '.message .datePermalink .DateTime'
    chapter_edit_date: '.messageInfo .editDate .DateTime'
    story_pub_date: '.message .datePermalink .DateTime'
    threadmark_list_item: '.threadmarkListItem a'
    chapter_threadmark_text: 'Threadmarks'
    chapter_content: '.messageContent .messageText'

parahumans.wordpress.com:
  scraper: 'TOCScraper'
  data:
    image_background: '#fff'
    toc_url: https://parahumans.wordpress.com/table-of-contents/
    title: Worm
    author: Wildbow
    cover_image_url: https://parahumans.files.wordpress.com/2012/08/skitter-cover-2-a.jpg?w=584&h=584
    chapter_urls: '#content .entry-content a:not(.sd-button)'
    chapter_content: '.entry-content'
    chapter_title: '.entry-title'
    content_filters:
      - 'a:contains("Next Chapter")'
      - 'a:contains("Last Chapter")'
      - '.sharedaddy'

unsongbook.com:
  scraper: 'TOCScraper'
  data:
    image_background: '#fff'
    toc_url: http://unsongbook.com/
    title: Unsong
    author: 'Scott Alexander'
    cover_image_url: http://unsongbook.com/wp-content/uploads/2016/01/icon2.png
    chapter_urls: '.pjgm-postcontent a:not(.share-icon)'
    chapter_content: '.pjgm-postcontent'
    chapter_title: '.pjgm-posttitle'
    content_filters:
      - '.sharedaddy'

practicalguidetoevil.wordpress.com:
  scraper: 'TOCScraper'
  data:
    image_background: '#fff'
    toc_url: https://practicalguidetoevil.wordpress.com/table-of-contents/
    title: A Practical Guide to Evil
    author: 'ErraticErrata'
    cover_image_url: http://orig02.deviantart.net/58b9/f/2016/131/4/b/catherine_foundling_by_sandara-da26nur.jpg
    chapter_urls: '.entry-content ul li a'
    chapter_content: '.entry-content'
    chapter_title: '.entry-header .entry-title'
    content_filters:
      - '.wpcnt'
      - '.sharedaddy'
    toc_filters:
      - '.sharedaddy'
